from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path

from virtuoso.obsidian_export import (
    MANIFEST_NAME,
    STUB_SCHEMA,
    ObsidianExporter,
    ObsidianExportError,
)
from virtuoso.workspace import WorkspaceService

ANSWER = "Retrieval changes memory and strengthens later access."
HINT = "Compare retrieval with rereading."
FOLLOW_UP = "Give one coding example."


class ObsidianExportTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name).resolve()
        self.workspace_root = root / "learner"
        self.out = root / "vault" / "07-learning" / "virtuoso" / "workspace-items"
        self.workspace = WorkspaceService.init(self.workspace_root)
        self._add("testing-effect", "Explain the testing effect")
        self._add("spacing-effect", "Explain the spacing effect")

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _add(self, item_id: str, title: str) -> None:
        self.workspace.add_item(
            item_id=item_id,
            title=title,
            focus="learning-science",
            prompt="Why does active recall improve memory?",
            answer=ANSWER,
            hint=HINT,
            follow_up=FOLLOW_UP,
        )

    def _run_cli(self, *args: str, expected: int = 0) -> subprocess.CompletedProcess[str]:
        completed = subprocess.run(
            [
                sys.executable,
                "-m",
                "virtuoso.cli",
                "--workspace",
                str(self.workspace_root),
                *args,
            ],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(
            completed.returncode,
            expected,
            msg=f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
        )
        return completed

    def _snapshot(self) -> dict[str, bytes]:
        return {
            child.name: child.read_bytes()
            for child in sorted(self.out.iterdir())
        }

    def test_export_writes_one_stub_per_queue_item_with_frontmatter_only(self) -> None:
        now = datetime(2026, 9, 4, 12, 0, tzinfo=timezone.utc)
        result = ObsidianExporter(self.workspace).export(self.out, now=now)

        self.assertEqual(result.stub_count, 2)
        self.assertEqual(result.new_count, 2)
        self.assertEqual(result.due_count, 0)
        self.assertEqual(
            sorted(child.name for child in self.out.iterdir()),
            [MANIFEST_NAME, "spacing-effect.md", "testing-effect.md"],
        )

        text = (self.out / "testing-effect.md").read_text(encoding="utf-8")
        self.assertIn(f'schema: "{STUB_SCHEMA}"', text)
        self.assertIn('item_id: "testing-effect"', text)
        self.assertIn('title: "Explain the testing effect"', text)
        self.assertIn('status: "new"', text)
        self.assertIn("next_review: null", text)
        self.assertIn('schedule_owner: "virtuoso-workspace"', text)
        self.assertIn("generated: true", text)
        self.assertIn('generated_at: "2026-09-04T12:00:00+00:00"', text)

        # No learning content leaves the workspace.
        self.assertNotIn(ANSWER, text)
        self.assertNotIn(HINT, text)
        self.assertNotIn(FOLLOW_UP, text)
        self.assertNotIn("Why does active recall", text)

        manifest = json.loads((self.out / MANIFEST_NAME).read_text(encoding="utf-8"))
        self.assertEqual(manifest["schema"], "virtuoso/obsidian-export@0.1")
        self.assertEqual(manifest["items"], ["spacing-effect", "testing-effect"])

    def test_second_export_at_same_instant_is_byte_identical(self) -> None:
        now = datetime(2026, 9, 4, 12, 0, tzinfo=timezone.utc)
        ObsidianExporter(self.workspace).export(self.out, now=now)
        first = self._snapshot()
        ObsidianExporter(self.workspace).export(self.out, now=now)
        self.assertEqual(self._snapshot(), first)

    def test_export_refuses_a_target_with_foreign_files(self) -> None:
        self.out.mkdir(parents=True)
        (self.out / "my-own-note.md").write_text("# mine\n", encoding="utf-8")

        with self.assertRaises(ObsidianExportError) as caught:
            ObsidianExporter(self.workspace).export(self.out)
        self.assertIn("not generated by Virtuoso", str(caught.exception))
        self.assertIn("my-own-note.md", str(caught.exception))
        # The foreign file is untouched.
        self.assertEqual((self.out / "my-own-note.md").read_text(encoding="utf-8"), "# mine\n")

    def test_export_refuses_a_target_inside_the_workspace(self) -> None:
        with self.assertRaises(ObsidianExportError) as caught:
            ObsidianExporter(self.workspace).export(self.workspace_root / "export")
        self.assertIn("outside the Virtuoso workspace", str(caught.exception))

    def test_export_removes_stubs_for_items_that_left_the_queue(self) -> None:
        now = datetime(2026, 9, 4, 12, 0, tzinfo=timezone.utc)
        ObsidianExporter(self.workspace).export(self.out, now=now)
        self.assertTrue((self.out / "spacing-effect.md").exists())

        self.workspace.retire_item("spacing-effect")
        result = ObsidianExporter(self.workspace).export(self.out, now=now)

        self.assertEqual(result.removed_count, 1)
        self.assertEqual(result.stub_count, 1)
        self.assertFalse((self.out / "spacing-effect.md").exists())
        self.assertTrue((self.out / "testing-effect.md").exists())

    def test_export_reflects_due_state_after_an_attempt(self) -> None:
        from virtuoso.practice import PracticeService

        attempt_at = datetime(2026, 9, 4, 12, 0, tzinfo=timezone.utc)
        PracticeService(self.workspace).run_administered(
            item_id="testing-effect",
            response="Retrieval strengthens memory.",
            result="not-demonstrated",
            confidence=1,
            agent_help="none",
            now=attempt_at,
        )
        later = datetime(2026, 9, 5, 12, 0, tzinfo=timezone.utc)
        result = ObsidianExporter(self.workspace).export(self.out, now=later)

        self.assertEqual(result.due_count, 1)
        text = (self.out / "testing-effect.md").read_text(encoding="utf-8")
        self.assertIn('status: "due"', text)
        self.assertNotIn("next_review: null", text)

    def test_export_never_writes_to_the_workspace_database(self) -> None:
        db = self.workspace_root / ".virtuoso" / "state.sqlite3"
        before = db.read_bytes()
        ObsidianExporter(self.workspace).export(
            self.out, now=datetime(2026, 9, 4, 12, 0, tzinfo=timezone.utc)
        )
        self.assertEqual(db.read_bytes(), before)

    def test_cli_export_obsidian_json_contract(self) -> None:
        completed = self._run_cli("export", "obsidian", "--out", str(self.out), "--json")
        payload = json.loads(completed.stdout)
        self.assertEqual(payload["schema"], "virtuoso/obsidian-export@0.1")
        self.assertEqual(payload["stub_count"], 2)
        self.assertEqual(
            sorted(stub["item_id"] for stub in payload["stubs"]),
            ["spacing-effect", "testing-effect"],
        )
        self.assertTrue((self.out / "testing-effect.md").exists())

    def test_cli_export_reports_foreign_files_as_a_workspace_error(self) -> None:
        self.out.mkdir(parents=True)
        (self.out / "keep-me.md").write_text("# keep\n", encoding="utf-8")
        completed = self._run_cli(
            "export", "obsidian", "--out", str(self.out), expected=2
        )
        self.assertIn("not generated by Virtuoso", completed.stderr)


if __name__ == "__main__":
    unittest.main()
