"""One-way, read-only projection of the workspace queue into Markdown stubs.

Obsidian Bases index Markdown frontmatter, not SQLite. This module writes a
folder of small generated notes that mirror the current review queue so a
Base can show what is due without a second scheduler.

Ownership rules:

- The export reads the workspace through the same review-queue rule that
  ``review due`` uses. It never writes to the workspace database.
- Every run rewrites the whole target folder. There is no merge logic.
- Stubs carry frontmatter only. No answer, hint, follow-up, or learning-unit
  prose leaves the workspace.
- The target folder must be empty or contain only earlier stubs from this
  export. The export refuses to delete anything it did not generate.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .errors import VirtuosoError
from .review import ReviewService
from .workspace import WorkspaceError, WorkspaceService

EXPORT_SCHEMA = "virtuoso/obsidian-export@0.1"
STUB_SCHEMA = "virtuoso/obsidian-stub@0.1"
MANIFEST_NAME = ".virtuoso-export.json"
SCHEDULE_OWNER = "virtuoso-workspace"

_ITEM_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")


class ObsidianExportError(VirtuosoError):
    """The export cannot run safely."""


@dataclass(frozen=True)
class ExportedStub:
    item_id: str
    title: str
    focus: str
    status: str
    due_at: str | None
    project_ids: tuple[str, ...]
    content_hash: str
    relative_path: str


@dataclass(frozen=True)
class ExportResult:
    schema: str
    generated_at: str
    output_dir: str
    stub_count: int
    due_count: int
    new_count: int
    removed_count: int
    stubs: tuple[ExportedStub, ...]

    def to_dict(self) -> dict[str, object]:
        return {
            "schema": self.schema,
            "generated_at": self.generated_at,
            "output_dir": self.output_dir,
            "stub_count": self.stub_count,
            "due_count": self.due_count,
            "new_count": self.new_count,
            "removed_count": self.removed_count,
            "stubs": [
                {
                    "item_id": stub.item_id,
                    "status": stub.status,
                    "due_at": stub.due_at,
                    "focus": stub.focus,
                    "relative_path": stub.relative_path,
                }
                for stub in self.stubs
            ],
        }


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _yaml_list(values: tuple[str, ...]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(_yaml_scalar(value) for value in values) + "]"


def render_stub(
    *,
    item_id: str,
    title: str,
    focus: str,
    status: str,
    due_at: str | None,
    project_ids: tuple[str, ...],
    content_hash: str,
    generated_at: str,
) -> str:
    """Render one generated note. Frontmatter only, no learning content."""
    next_review = _yaml_scalar(due_at) if due_at is not None else "null"
    lines = [
        "---",
        f"schema: {_yaml_scalar(STUB_SCHEMA)}",
        f"item_id: {_yaml_scalar(item_id)}",
        f"title: {_yaml_scalar(title)}",
        f"focus: {_yaml_scalar(focus)}",
        f"status: {_yaml_scalar(status)}",
        f"next_review: {next_review}",
        f"project_ids: {_yaml_list(project_ids)}",
        f"schedule_owner: {_yaml_scalar(SCHEDULE_OWNER)}",
        f"content_hash: {_yaml_scalar(content_hash)}",
        f"generated_at: {_yaml_scalar(generated_at)}",
        "generated: true",
        "---",
        "",
        f"# {title}",
        "",
        "Generated by Virtuoso from the workspace review queue. "
        "Edits here are overwritten on the next export. "
        "Practice through the Virtuoso CLI or plugin, not this note.",
        "",
    ]
    return "\n".join(lines)


def _generated_by_us(path: Path) -> bool:
    if not path.is_file() or path.suffix != ".md":
        return False
    try:
        with path.open("r", encoding="utf-8") as handle:
            head = handle.read(600)
    except OSError:
        return False
    return f"schema: {_yaml_scalar(STUB_SCHEMA)}" in head and "generated: true" in head


class ObsidianExporter:
    def __init__(self, workspace: WorkspaceService) -> None:
        self.workspace = workspace

    def _titles(self) -> dict[str, str]:
        titles: dict[str, str] = {}
        with self.workspace._connect() as db:  # noqa: SLF001 - read-only SELECT
            db.execute("PRAGMA query_only = 1")
            for row in db.execute(
                "SELECT item_id, title FROM items WHERE retired_at IS NULL"
            ):
                titles[row["item_id"]] = row["title"]
        return titles

    def export(
        self, output_dir: Path, *, now: datetime | None = None
    ) -> ExportResult:
        observed_at = now or datetime.now(timezone.utc)
        if observed_at.tzinfo is None or observed_at.utcoffset() is None:
            raise ObsidianExportError("export timestamp must be timezone-aware")
        observed_at = observed_at.astimezone(timezone.utc)
        generated_at = observed_at.isoformat()

        output_dir = Path(output_dir)
        if output_dir.exists() and output_dir.is_symlink():
            raise ObsidianExportError(
                f"export target must not be a symlink: {output_dir}"
            )
        if output_dir.exists() and not output_dir.is_dir():
            raise ObsidianExportError(
                f"export target is not a directory: {output_dir}"
            )
        try:
            resolved_target = output_dir.resolve()
            workspace_root = self.workspace.root.resolve()
        except OSError as exc:
            raise ObsidianExportError(f"cannot resolve export target: {exc}") from exc
        if resolved_target == workspace_root or workspace_root in resolved_target.parents:
            raise ObsidianExportError(
                "export target must live outside the Virtuoso workspace"
            )

        try:
            queue = ReviewService(self.workspace).due(now=observed_at)
            titles = self._titles()
        except WorkspaceError as exc:
            raise ObsidianExportError(str(exc)) from exc

        # Refuse to destroy anything we did not generate.
        foreign: list[str] = []
        existing_stubs: list[Path] = []
        if output_dir.exists():
            for child in sorted(output_dir.iterdir()):
                if child.name == MANIFEST_NAME:
                    continue
                if child.is_dir():
                    foreign.append(child.name)
                    continue
                if _generated_by_us(child):
                    existing_stubs.append(child)
                else:
                    foreign.append(child.name)
        if foreign:
            raise ObsidianExportError(
                "export target contains files not generated by Virtuoso; "
                "choose an empty folder or remove them first: "
                + ", ".join(foreign[:5])
                + (" ..." if len(foreign) > 5 else "")
            )

        stubs: list[ExportedStub] = []
        rendered: dict[str, str] = {}
        for item in queue:
            if not _ITEM_ID.fullmatch(item.item_id):
                raise ObsidianExportError(
                    f"item id is not a safe file name: {item.item_id!r}"
                )
            title = titles.get(item.item_id, item.item_id)
            relative_path = f"{item.item_id}.md"
            rendered[relative_path] = render_stub(
                item_id=item.item_id,
                title=title,
                focus=item.focus,
                status=item.status,
                due_at=item.due_at,
                project_ids=tuple(item.project_ids),
                content_hash=item.content_hash,
                generated_at=generated_at,
            )
            stubs.append(
                ExportedStub(
                    item_id=item.item_id,
                    title=title,
                    focus=item.focus,
                    status=item.status,
                    due_at=item.due_at,
                    project_ids=tuple(item.project_ids),
                    content_hash=item.content_hash,
                    relative_path=relative_path,
                )
            )

        try:
            output_dir.mkdir(parents=True, exist_ok=True)
            removed = 0
            for stale in existing_stubs:
                if stale.name not in rendered:
                    stale.unlink()
                    removed += 1
            for relative_path, text in rendered.items():
                target = output_dir / relative_path
                if target.is_symlink():
                    raise ObsidianExportError(
                        f"refusing to write through a symlink: {target}"
                    )
                tmp = output_dir / f".{relative_path}.tmp"
                tmp.write_text(text, encoding="utf-8")
                os.replace(tmp, target)
            manifest = {
                "schema": EXPORT_SCHEMA,
                "generated_at": generated_at,
                "workspace": str(workspace_root),
                "stub_count": len(stubs),
                "items": [stub.item_id for stub in stubs],
            }
            manifest_tmp = output_dir / f".{MANIFEST_NAME}.tmp"
            manifest_tmp.write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            os.replace(manifest_tmp, output_dir / MANIFEST_NAME)
        except OSError as exc:
            raise ObsidianExportError(f"export write failed: {exc}") from exc

        return ExportResult(
            schema=EXPORT_SCHEMA,
            generated_at=generated_at,
            output_dir=str(output_dir),
            stub_count=len(stubs),
            due_count=sum(1 for stub in stubs if stub.status == "due"),
            new_count=sum(1 for stub in stubs if stub.status == "new"),
            removed_count=removed,
            stubs=tuple(stubs),
        )
