"""Retrieval over learning items: FTS5 lexical + embedding kNN.

RAG support. Two retrieval surfaces over the items the CLI already owns:

- **Lexical**: an FTS5 index (porter tokenizer, so "goroutine" finds
  "goroutines") over item titles, prompts, answers and hints.
- **Semantic**: an embedding table plus exact cosine kNN. Virtuoso never
  calls an embedding API: an external embedder (agent, script, module)
  produces vectors and calls ``embed_upsert``. The core stays offline
  and deterministic.

Storage boundary (found the hard way 2026-09-02): the workspace state
database validates its exact object set and rejects extra tables, so
the retrieval index lives in its OWN derived database,
``.virtuoso/search.sqlite3``. It is fully rebuildable from items and
embeddings at any time and is never part of evidence. Deleting the file
loses nothing that cannot be regenerated by re-running the embedder;
lexical rows rebuild automatically on first search.
"""

from __future__ import annotations

import hashlib
import json
import math
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .errors import VirtuosoError
from .workspace import WorkspaceService

_FTS_TABLE = "item_fts"
_EMBED_TABLE = "item_embeddings"
_METADATA_TABLE = "search_metadata"
_LEXICAL_FINGERPRINT_KEY = "lexical_fingerprint"


class SearchError(VirtuosoError):
    """A retrieval request cannot be served against this workspace."""


@dataclass(frozen=True)
class SearchHit:
    item_id: str
    score: float
    snippet: str


@dataclass(frozen=True)
class SemanticHit:
    item_id: str
    score: float


def index_path(service: WorkspaceService) -> Path:
    return service.state_dir / "search.sqlite3"


def _connect_index(service: WorkspaceService) -> sqlite3.Connection:
    path = index_path(service)
    db = sqlite3.connect(path, timeout=5.0)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA foreign_keys = ON")
    return db


def _ensure_schema(db: sqlite3.Connection) -> None:
    db.execute(
        f"""
        CREATE VIRTUAL TABLE IF NOT EXISTS {_FTS_TABLE} USING fts5(
            item_id UNINDEXED,
            title,
            prompt,
            answer,
            hint,
            tokenize='porter unicode61'
        )
        """
    )
    db.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_EMBED_TABLE} (
            item_id TEXT NOT NULL,
            model TEXT NOT NULL,
            dim INTEGER NOT NULL CHECK(dim > 0),
            vector_json TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY(item_id, model)
        )
        """
    )
    db.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {_METADATA_TABLE} (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
        """
    )


def _active_items(service: WorkspaceService) -> tuple[tuple[str, str], ...]:
    with service._connect() as source:
        rows = source.execute(
            "SELECT item_id, content_hash FROM items "
            "WHERE retired_at IS NULL ORDER BY item_id"
        ).fetchall()
    return tuple((row["item_id"], row["content_hash"]) for row in rows)


def _lexical_fingerprint(active_items: tuple[tuple[str, str], ...]) -> str:
    payload = json.dumps(active_items, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _stored_fingerprint(db: sqlite3.Connection) -> str | None:
    row = db.execute(
        f"SELECT value FROM {_METADATA_TABLE} WHERE key = ?",
        (_LEXICAL_FINGERPRINT_KEY,),
    ).fetchone()
    return row["value"] if row is not None else None


def _reindex_lexical(
    service: WorkspaceService,
    db: sqlite3.Connection,
    *,
    active_items: tuple[tuple[str, str], ...],
    fingerprint: str,
) -> None:
    """Rebuild the lexical index from current non-retired items."""
    db.execute(f"DELETE FROM {_FTS_TABLE}")
    for item_id, _content_hash in active_items:
        item = service.load_item(item_id)
        db.execute(
            f"INSERT INTO {_FTS_TABLE}(item_id, title, prompt, answer, hint) "
            "VALUES (?, ?, ?, ?, ?)",
            (item.item_id, item.title, item.prompt, item.answer, item.hint or ""),
        )
    db.execute(
        f"""
        INSERT INTO {_METADATA_TABLE}(key, value) VALUES (?, ?)
        ON CONFLICT(key) DO UPDATE SET value = excluded.value
        """,
        (_LEXICAL_FINGERPRINT_KEY, fingerprint),
    )
    db.commit()


def _fresh_index(service: WorkspaceService) -> sqlite3.Connection:
    db = _connect_index(service)
    try:
        _ensure_schema(db)
        active_items = _active_items(service)
        fingerprint = _lexical_fingerprint(active_items)
        indexed = db.execute(f"SELECT COUNT(*) FROM {_FTS_TABLE}").fetchone()[0]
        if (
            indexed != len(active_items)
            or _stored_fingerprint(db) != fingerprint
        ):
            _reindex_lexical(
                service,
                db,
                active_items=active_items,
                fingerprint=fingerprint,
            )
        return db
    except Exception:
        db.close()
        raise


def _plain_fts_query(query: str) -> str:
    return " ".join(
        '"' + token.replace('"', '""') + '"' for token in query.split()
    )


def lexical_search(
    service: WorkspaceService, query: str, *, limit: int = 10
) -> list[SearchHit]:
    """FTS5 MATCH over item text. Plain word queries; BM25-ranked."""
    query = (query or "").strip()
    if not query:
        raise SearchError("lexical query must be non-empty")
    if not 1 <= limit <= 100:
        raise SearchError("limit must be between 1 and 100")
    plain_query = _plain_fts_query(query)
    db = _fresh_index(service)
    try:
        rows = db.execute(
            f"""
            SELECT item_id, bm25({_FTS_TABLE}) AS rank,
                   snippet({_FTS_TABLE}, -1, '', '…', ' ', 12) AS snip
            FROM {_FTS_TABLE}
            WHERE {_FTS_TABLE} MATCH ?
            ORDER BY rank
            LIMIT ?
            """,
            (plain_query, limit),
        ).fetchall()
    except sqlite3.OperationalError as exc:
        raise SearchError(f"invalid lexical query {query!r}: {exc}") from exc
    finally:
        db.close()
    return [
        SearchHit(item_id=row["item_id"], score=-row["rank"], snippet=row["snip"])
        for row in rows
    ]


def _unit(vector: list[float]) -> list[float]:
    try:
        values = [float(v) for v in vector]
    except (TypeError, ValueError) as exc:
        raise SearchError("embedding vector must contain only numbers") from exc
    if not values or any(math.isnan(v) or math.isinf(v) for v in values):
        raise SearchError("embedding vector must be finite and non-empty")
    norm = math.sqrt(sum(v * v for v in values))
    if norm == 0.0:
        raise SearchError("embedding vector must not be the zero vector")
    return [v / norm for v in values]


def embed_upsert(
    service: WorkspaceService,
    *,
    item_id: str,
    model: str,
    vector: list[float],
) -> None:
    """Store or replace an embedding for one item under one model."""
    if not (model or "").strip():
        raise SearchError("embedding model id must be non-empty")
    unit = _unit(vector)
    service.load_item(item_id)  # fails closed on unknown items
    db = _fresh_index(service)
    try:
        db.execute("BEGIN IMMEDIATE")
        dimensions = {
            row["dim"]
            for row in db.execute(
                f"SELECT DISTINCT dim FROM {_EMBED_TABLE} WHERE model = ?",
                (model,),
            ).fetchall()
        }
        if dimensions and dimensions != {len(unit)}:
            stored = ", ".join(str(dimension) for dimension in sorted(dimensions))
            raise SearchError(
                f"embedding dimension mismatch for model {model!r}: "
                f"stored {stored}, new {len(unit)}; a model id must identify "
                "one fixed dimensionality"
            )
        db.execute(
            f"""
            INSERT INTO {_EMBED_TABLE}(item_id, model, dim, vector_json, updated_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(item_id, model) DO UPDATE SET
                dim = excluded.dim,
                vector_json = excluded.vector_json,
                updated_at = excluded.updated_at
            """,
            (
                item_id,
                model,
                len(unit),
                json.dumps(unit),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        db.commit()
    finally:
        db.close()


def semantic_search(
    service: WorkspaceService,
    *,
    model: str,
    query_vector: list[float],
    limit: int = 10,
) -> list[SemanticHit]:
    """Exact cosine kNN over stored embeddings for one model."""
    if not 1 <= limit <= 100:
        raise SearchError("limit must be between 1 and 100")
    query_unit = _unit(query_vector)
    active_item_ids = {
        item_id for item_id, _content_hash in _active_items(service)
    }
    db = _fresh_index(service)
    try:
        rows = db.execute(
            f"SELECT item_id, dim, vector_json FROM {_EMBED_TABLE} WHERE model = ?",
            (model,),
        ).fetchall()
    finally:
        db.close()
    hits: list[SemanticHit] = []
    for row in rows:
        if row["item_id"] not in active_item_ids:
            continue
        stored = json.loads(row["vector_json"])
        if len(stored) != len(query_unit):
            raise SearchError(
                f"embedding dimension mismatch for item {row['item_id']}: "
                f"stored {row['dim']}, query {len(query_unit)}; a model id must "
                "identify one fixed dimensionality"
            )
        score = sum(a * b for a, b in zip(query_unit, stored))
        hits.append(SemanticHit(item_id=row["item_id"], score=round(score, 6)))
    hits.sort(key=lambda hit: (-hit.score, hit.item_id))
    return hits[:limit]


def search_status(service: WorkspaceService) -> dict[str, Any]:
    """Index health: lexical freshness and embedding inventory."""
    active_items = _active_items(service)
    active = len(active_items)
    active_fingerprint = _lexical_fingerprint(active_items)
    path = index_path(service)
    if not path.is_file():
        return {
            "schema": "virtuoso/search-status@0.1",
            "index": str(path),
            "exists": False,
            "lexical_index_rows": 0,
            "active_items": active,
            "lexical_fresh": False,
            "fingerprint": None,
            "embedding_models": [],
        }
    db = _fresh_index(service)
    try:
        fts_rows = db.execute(f"SELECT COUNT(*) FROM {_FTS_TABLE}").fetchone()[0]
        embed_rows = db.execute(
            f"SELECT model, COUNT(*) AS n FROM {_EMBED_TABLE} GROUP BY model"
        ).fetchall()
        fingerprint = _stored_fingerprint(db)
    finally:
        db.close()
    return {
        "schema": "virtuoso/search-status@0.1",
        "index": str(path),
        "exists": True,
        "lexical_index_rows": fts_rows,
        "active_items": active,
        "lexical_fresh": fts_rows == active and fingerprint == active_fingerprint,
        "fingerprint": fingerprint,
        "embedding_models": [
            {"model": row["model"], "vectors": row["n"]} for row in embed_rows
        ],
    }
