import { test, expect } from '@playwright/test'

test.beforeEach(async ({ request }) => { await request.post('/test/reset') })

test('desktop interface completes a real backend study and measured review', async ({ page, request }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Start next action' }).click()
  await expect(page.getByRole('button', { name: 'Finish study' })).toBeVisible()
  await expect(page.getByText('Why does retrieval practice help?', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('study.png') })
  let evidence = await (await request.get('/test/evidence')).json()
  expect(evidence.study).toHaveLength(0)
  await page.getByRole('button', { name: 'Finish study' }).click()
  await expect(page.getByText('Study recorded. Your first recall is ready.')).toBeVisible()
  evidence = await (await request.get('/test/evidence')).json()
  expect(evidence.study).toHaveLength(1)
  expect(evidence.attempts).toHaveLength(0)
  expect(evidence.proposals).toHaveLength(0)
  await page.getByRole('button', { name: 'Start next action' }).click()
  await expect(page.getByText('Why does retrieval practice help?', { exact: true })).toBeVisible()
  await expect(page.getByText('Retrieval strengthens later access to a memory.', { exact: true })).toHaveCount(0)
  await page.getByLabel('Your response', { exact: true }).fill('Practising recall strengthens later access.')
  await page.getByRole('button', { name: 'Save response', exact: true }).click()
  await page.getByRole('button', { name: 'Try once more unaided' }).click()
  await page.getByLabel('Your retry', { exact: true }).fill('It strengthens retrieval paths.')
  await page.getByRole('button', { name: 'Save retry', exact: true }).click()
  await page.getByRole('button', { name: 'Show hint' }).click()
  await page.getByLabel('I used notes').check()
  await page.getByRole('button', { name: 'Reveal answer' }).click()
  await expect(page.getByText('Retrieval strengthens later access to a memory.', { exact: true })).toBeVisible()
  await page.getByLabel('Result', { exact: true }).selectOption('partial')
  await page.screenshot({ path: testInfo.outputPath('grade.png') })
  await page.getByRole('button', { name: 'Record result', exact: true }).click()
  await expect(page.getByText('Practice recorded.')).toBeVisible()
  evidence = await (await request.get('/test/evidence')).json()
  expect(evidence.attempts).toHaveLength(1)
  expect(evidence.proposals).toHaveLength(1)
  expect(evidence.attempts[0].administered).toBe(false)
  expect(evidence.attempts[0].initial_latency_ms).toBeGreaterThan(0)
  expect(evidence.attempts[0].open_notes).toBe(true)
  await page.reload()
  await expect(page.getByLabel('Your response', { exact: true })).toHaveCount(0)
  const after = await (await request.get('/test/evidence')).json()
  expect(after.attempts).toHaveLength(1)
  expect(after.study).toHaveLength(1)
  expect(errors).toEqual([])
})

test('narrow layout and unavailable backend stay usable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start next action' }).click()
  await expect(page.getByRole('button', { name: 'Finish study' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('narrow.png') })
  await page.route('**/api/plugins/virtuoso/context', route => route.fulfill({ status: 404, body: 'Disabled backend' }))
  await page.reload()
  await expect(page.getByText('The Virtuoso backend is unavailable.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Check connection' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start next action' })).toHaveCount(0)
})
